In [1]:
##List
n=[6,7,8,9]

In [4]:
n[1:3]  ### [start_index: end_index]

[7, 8]

In [5]:
n[-1]

9

In [6]:
import numpy as np

In [7]:
a=np.array([6,7,8])

In [8]:
a[0:2]

array([6, 7])

In [9]:
a[-1]

8

In [11]:
a=np.array([[6,7,8],[1,2,3],[7,8,9]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [7, 8, 9]])

In [17]:
a[2,:]

array([7, 8, 9])

In [16]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [8, 9]])

In [14]:
a[2,0:2]

array([7, 8])

In [12]:
a[1,2]

3

In [13]:
a[0:2,2]

array([8, 3])

In [18]:
### Iterate through an array

a=np.array([[6,7,8],[1,2,3],[7,8,9]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [7, 8, 9]])

In [19]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[7 8 9]


In [21]:
## flattening this 2d array into a 1-D array
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
7
8
9


In [23]:
#### Stacking through arrays together
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [26]:
b=np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [27]:
## vertical stack of a over b
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [28]:
## horizontal stack, side-ways
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [29]:
## Horizontal split
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [32]:
np.hsplit(a,5)

[array([[ 0,  1,  2],
        [15, 16, 17]]),
 array([[ 3,  4,  5],
        [18, 19, 20]]),
 array([[ 6,  7,  8],
        [21, 22, 23]]),
 array([[ 9, 10, 11],
        [24, 25, 26]]),
 array([[12, 13, 14],
        [27, 28, 29]])]

In [35]:
v=np.vsplit(a,2)

In [36]:
v[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [37]:
v[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [38]:
### Indexing with boolean arrays

In [39]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [42]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [43]:
a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [44]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
for x in np.nditer(a,order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [47]:
for x in np.nditer(a,order='F', flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [48]:
## Linear algebra

In [50]:
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [51]:
b=np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [54]:
np.matmul(a,b) ##matrix multiplication

array([[6., 6.],
       [6., 6.]])

In [56]:
c=np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
np.linalg.det(c)

1.0

In [58]:
##Statistics

a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
np.sum(a)

21

In [64]:
np.sum(a, axis=0)  ##row

array([5, 7, 9])

In [59]:
np.min(a)

1

In [60]:
np.max(a)

6

In [62]:
np.max(a, axis=1) ###axis=0(ROW) axis=1(COLUMN)

array([3, 6])

## Pandas

In [65]:
import pandas as pd

In [67]:
x=['a','b','c','d','e']
y=[1,2,3,4,5]
type(x)

list

In [70]:
a=pd.Series(x,y)
a

1    a
2    b
3    c
4    d
5    e
dtype: object

In [69]:
type(a)

pandas.core.series.Series

In [72]:
## creating a dataframe 
r=np.random.randint(1,25,(5,4))
r

array([[ 1,  2,  8,  6],
       [24, 24, 19,  9],
       [13, 13, 23, 19],
       [16, 19,  2, 16],
       [20,  3, 20, 10]])

In [73]:
df=pd.DataFrame(r)
df

0   1   2   3
0   1   2   8   6
1  24  24  19   9
2  13  13  23  19
3  16  19   2  16
4  20   3  20  10

In [74]:
df=pd.DataFrame(r,['a','b','c','d','e'],['w','x','y','z'])
df

w   x   y   z
a   1   2   8   6
b  24  24  19   9
c  13  13  23  19
d  16  19   2  16
e  20   3  20  10

In [75]:
type(df)

pandas.core.frame.DataFrame

In [90]:
df['s']=df['y']+df['z']  ### create a new column
df

w   x   y   z   s
a   1   2   8   6  14
b  24  24  19   9  28
c  13  13  23  19  42
d  16  19   2  16  18

In [79]:
### drop a specific row/column
df.drop('e')

w   x   y   z   s
a   1   2   8   6  14
b  24  24  19   9  28
c  13  13  23  19  42
d  16  19   2  16  18

In [82]:
df.drop('s', axis=1)

w   x   y   z
a   1   2   8   6
b  24  24  19   9
c  13  13  23  19
d  16  19   2  16
e  20   3  20  10

In [83]:
df

w   x   y   z   s
a   1   2   8   6  14
b  24  24  19   9  28
c  13  13  23  19  42
d  16  19   2  16  18
e  20   3  20  10  30

In [84]:
df.drop('e', inplace=True)  ### To permanently drop the row/column

In [85]:
df

w   x   y   z   s
a   1   2   8   6  14
b  24  24  19   9  28
c  13  13  23  19  42
d  16  19   2  16  18

In [87]:
df.drop('s', axis=1, inplace=True)

In [91]:
df

w   x   y   z   s
a   1   2   8   6  14
b  24  24  19   9  28
c  13  13  23  19  42
d  16  19   2  16  18

## Indexing and slicing in matrix/dataframe
* .loc - name/labels of rows and columns
* .iloc - index values

In [95]:
df

w   x   y   z   s
a   1   2   8   6  14
b  24  24  19   9  28
c  13  13  23  19  42
d  16  19   2  16  18

In [99]:
df.loc['c','z']

19

In [96]:
df.loc['b']

w    24
x    24
y    19
z     9
s    28
Name: b, dtype: int32

In [97]:
df.loc['b','y']

19

In [100]:
df

w   x   y   z   s
a   1   2   8   6  14
b  24  24  19   9  28
c  13  13  23  19  42
d  16  19   2  16  18

In [103]:
df.loc['c':'d','y':'s']

y   z   s
c  23  19  42
d   2  16  18

In [101]:
df.loc['a':'b','x':'y']

x   y
a   2   8
b  24  19

In [104]:
df

w   x   y   z   s
a   1   2   8   6  14
b  24  24  19   9  28
c  13  13  23  19  42
d  16  19   2  16  18

In [106]:
df.iloc[2:,1:4]

x   y   z
c  13  23  19
d  19   2  16

In [105]:
df.iloc[0:2,1:3]

x   y
a   2   8
b  24  19

In [107]:
df

w   x   y   z   s
a   1   2   8   6  14
b  24  24  19   9  28
c  13  13  23  19  42
d  16  19   2  16  18

In [108]:
df>6

w      x      y      z     s
a  False  False   True  False  True
b   True   True   True   True  True
c   True   True   True   True  True
d   True   True  False   True  True

In [109]:
df[df>6]  ###NaN - Not a number (Null values)

w     x     y     z   s
a   NaN   NaN   8.0   NaN  14
b  24.0  24.0  19.0   9.0  28
c  13.0  13.0  23.0  19.0  42
d  16.0  19.0   NaN  16.0  18

In [110]:
d={'a':[1,2,3,4,5], 'b':[6,8,9,10,np.nan], 'c':[11,12,4,np.nan,np.nan], 'd':[2,5,np.nan,np.nan,np.nan], 'e':[3,np.nan,np.nan,np.nan,np.nan]}
d

{'a': [1, 2, 3, 4, 5],
 'b': [6, 8, 9, 10, nan],
 'c': [11, 12, 4, nan, nan],
 'd': [2, 5, nan, nan, nan],
 'e': [3, nan, nan, nan, nan]}

In [111]:
d=pd.DataFrame(d)
d

a     b     c    d    e
0  1   6.0  11.0  2.0  3.0
1  2   8.0  12.0  5.0  NaN
2  3   9.0   4.0  NaN  NaN
3  4  10.0   NaN  NaN  NaN
4  5   NaN   NaN  NaN  NaN

In [112]:
## Drop the null values
d.dropna()

a    b     c    d    e
0  1  6.0  11.0  2.0  3.0

In [117]:
d.dropna(thresh=3) ### thresh value - means u need to have that many number of values

a    b     c    d    e
0  1  6.0  11.0  2.0  3.0
1  2  8.0  12.0  5.0  NaN
2  3  9.0   4.0  NaN  NaN

In [121]:
d.fillna(1)

a     b     c    d    e
0  1   6.0  11.0  2.0  3.0
1  2   8.0  12.0  5.0  1.0
2  3   9.0   4.0  1.0  1.0
3  4  10.0   1.0  1.0  1.0
4  5   1.0   1.0  1.0  1.0

In [122]:
d

a     b     c    d    e
0  1   6.0  11.0  2.0  3.0
1  2   8.0  12.0  5.0  NaN
2  3   9.0   4.0  NaN  NaN
3  4  10.0   NaN  NaN  NaN
4  5   NaN   NaN  NaN  NaN

In [128]:
d['b'].fillna(d['b'].mean(), inplace=True)

In [129]:
d

a      b     c    d    e
0  1   6.00  11.0  2.0  3.0
1  2   8.00  12.0  5.0  NaN
2  3   9.00   4.0  NaN  NaN
3  4  10.00   NaN  NaN  NaN
4  5   8.25   NaN  NaN  NaN

In [131]:
d['c'].fillna(d['c'].mean(), inplace=True)
d

a      b     c    d    e
0  1   6.00  11.0  2.0  3.0
1  2   8.00  12.0  5.0  NaN
2  3   9.00   4.0  NaN  NaN
3  4  10.00   9.0  NaN  NaN
4  5   8.25   9.0  NaN  NaN