## Numpy


In [2]:
import numpy as np

In [4]:
a=np.array([1,2,3])
print(a)  ###1-d array

[1 2 3]


In [11]:
a.shape

(3,)

In [12]:
a.ndim  ###get the dimension

1

In [17]:
a.size  ##total number of elements

3

In [20]:
a.dtype

dtype('int32')

In [19]:
a.itemsize

4

In [5]:
type(a)

numpy.ndarray

In [9]:
b=np.array([[2,3,4],[4,5,6]])
print(b)  ### 2-d array

[[2 3 4]
 [4 5 6]]


In [10]:
b.shape  ##(rows, columns)

(2, 3)

In [13]:
b.ndim

2

In [14]:
b.dtype  #### int32= 4 bytes (1byte=8bits)

dtype('int32')

In [15]:
b=np.array([[2,3,4],[4,5,6]], dtype="int16")
print(b)  ### 2-d array

[[2 3 4]
 [4 5 6]]


In [16]:
b.dtype

dtype('int16')

In [18]:
b.size

6

In [21]:
b.itemsize  ###equiv no. of bytes 

2

#### Access/change specific rows and columns  [row,column], startindex:endindex

In [44]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)   

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [86]:
a[0,1:6:2]    ####Important!!! ####Important!!! ####Important!!! ####Important!!!

array([2, 4, 6])

In [87]:
a[0,1:-1:2]

array([2, 4, 6])

In [88]:
a[0,3]

4

In [89]:
a.shape

(2, 7)

In [90]:
a[0,5]

6

In [91]:
a[:,2]

array([ 3, 10])

In [92]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [93]:
a[1,5]=22

In [94]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 22, 14]])

In [95]:
a[:,2]=5
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 22, 14]])

In [96]:
a[:,2]=9,10
a

array([[ 1,  2,  9,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 22, 14]])

## Initializing different types of array

In [97]:
## All zeros matrix

np.zeros(5) ## vector 

array([0., 0., 0., 0., 0.])

In [98]:
np.zeros((2,3))  ## 2-d matrix

array([[0., 0., 0.],
       [0., 0., 0.]])

In [99]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [100]:
## All ones matrix

np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [101]:
np.full((3,3,2), 109)

array([[[109, 109],
        [109, 109],
        [109, 109]],

       [[109, 109],
        [109, 109],
        [109, 109]],

       [[109, 109],
        [109, 109],
        [109, 109]]])

In [102]:
c = np.full_like(a,6)
print(c)

[[6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6]]


In [103]:
c.shape

(2, 7)

In [104]:
c.reshape(7,2)

array([[6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6]])

In [105]:
### Initialize a matrix of random numbers

np.random.rand(4,3)   ####Important!!!

array([[0.13053884, 0.72429221, 0.53334079],
       [0.55123812, 0.66241585, 0.15933155],
       [0.09759562, 0.52388649, 0.50356599],
       [0.97233964, 0.99720478, 0.42731397]])

In [106]:
np.random.random_sample(a.shape)

array([[0.92745177, 0.87219667, 0.54875854, 0.48337739, 0.66032712,
        0.09056309, 0.3654313 ],
       [0.52346551, 0.0900956 , 0.11125731, 0.8666918 , 0.3501635 ,
        0.55702811, 0.73370433]])

In [107]:
### Random integer values

np.random.randint(6, size=(3,3))   ####Important!!!

array([[1, 3, 3],
       [3, 2, 2],
       [4, 3, 4]])

In [108]:
np.random.randint(-8,8, size=(4,3))

array([[-8, -5,  4],
       [-5, -3, -7],
       [ 2, -6, -7],
       [-8,  3,  1]])

In [109]:
## Identity matrix

In [110]:
np.identity(3)  ### square matrix    ####Important!!!

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [111]:
np.identity(5)  ### square matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [112]:
### repeat an array

In [117]:
arr=np.array([[1,2,3]])
arr1=np.repeat(arr,3, axis=0)
print(arr1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [118]:
a=np.array([1,2,3])
b=a
b

array([1, 2, 3])

In [121]:
b[0]=900
b

array([900,   2,   3])

In [122]:
a

array([900,   2,   3])

In [124]:
a=np.array([1,2,3])
b=a.copy()
b[0]=900
b

array([900,   2,   3])

In [125]:
a

array([1, 2, 3])

In [134]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [135]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [136]:
a

array([1, 2, 3, 4])

In [137]:
a+=2
a

array([3, 4, 5, 6])

In [138]:
b=np.array([3,0,4,0])

In [140]:
a+b

array([6, 4, 9, 6])

In [141]:
a**b

array([ 27,   1, 625,   1], dtype=int32)

In [142]:
a

array([3, 4, 5, 6])

In [143]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [144]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

In [ ]:
##Linear algebra using np